version: '3.8'
services:
  extension:
    container_name: post_checkout
    build:
      context: .
      dockerfile: extension.Dockerfile
    env_file:
      - ocudev-ihor.bohdan-checkout-post-purchase/.env
    volumes:
      - .:/app
    command: /bin/sh -c "cd /app/ocudev-ihor.bohdan-checkout-post-purchase && yarn && yarn start --port=39351"
    ports:
      - '39351:39351'

  web:
    container_name: nv_shop
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s -b 0.0.0.0 --pid tmp/pids/server.pid"
    build: .
    env_file: .env
    volumes:
      - .:/app:rw
    tty: true
    stdin_open: true
    ports:
      - '3001:3000'
    depends_on:
      - db
      - sidekiq

  db:
    container_name: nv_shop_db
    image: postgres:14-alpine
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - data-postgres:/var/lib/postgresql/data

  redis:
    container_name: nv_shop_redis
    image: redis:latest
    command: redis-server
    ports:
      - '6379:6379'

  sidekiq:
    container_name: nv_shop_sidekiq
    command: bundle exec sidekiq
    build: .
    env_file: .env
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    depends_on:
      - db
      - redis

volumes:
  data-postgres:
    driver: local
