default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('POSTGRES_HOST') %>
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  port: <%= ENV.fetch('POSTGRES_PORT') %>
  pool: 5

development:
  <<: *default
  database: nv_shop_development


test:
  <<: *default
  database: nv_shop_test
